
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asuka-PC
 */
public class Framemodul7_1 extends javax.swing.JFrame {
    String temp="";
    Double ti, bt, hi;

    /**
     * Creates new form Framemodul7_1
     */
    public Framemodul7_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ideal = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        tinggi = new javax.swing.JTextField();
        bb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        keluar = new javax.swing.JButton();
        hitung = new javax.swing.JButton();
        coba = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        saran = new javax.swing.JTextField();
        hasil = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Jenis Kelamin");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 170, 70, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 10, 100, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 60, 70, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Tinggi");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 100, 70, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Berat Badan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 140, 70, 14);
        getContentPane().add(ideal);
        ideal.setBounds(220, 230, 40, 30);
        getContentPane().add(nama);
        nama.setBounds(170, 50, 150, 30);
        getContentPane().add(tinggi);
        tinggi.setBounds(170, 90, 60, 30);
        getContentPane().add(bb);
        bb.setBounds(170, 130, 60, 30);

        jLabel6.setText("cm");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 100, 20, 14);

        jLabel7.setText("kg");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 240, 11, 14);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Perempuan");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(160, 160, 100, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Laki-laki");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(260, 160, 90, 23);

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(240, 200, 80, 23);

        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung);
        hitung.setBounds(50, 200, 80, 23);

        coba.setText("Coba Lagi");
        coba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobaActionPerformed(evt);
            }
        });
        getContentPane().add(coba);
        coba.setBounds(140, 200, 90, 23);

        jLabel8.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(130, 280, 140, 14);

        jLabel9.setText("kg");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(240, 140, 20, 14);

        jLabel10.setText("Berat Badan Ideal Anda Adalah");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 240, 180, 14);
        getContentPane().add(saran);
        saran.setBounds(10, 340, 350, 30);

        hasil.setEditable(false);
        getContentPane().add(hasil);
        hasil.setBounds(10, 300, 350, 30);

        setBounds(0, 0, 394, 426);
    }// </editor-fold>//GEN-END:initComponents

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        if (nama.getText().equals("")||bb.getText().equals("")||tinggi.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Data masukan harus diisi semua");
        }else if (jRadioButton1.isSelected()||jRadioButton2.isSelected()) {
            try {
                Proses();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Inputan salah");
            } 
        }else{
            JOptionPane.showMessageDialog(null, "Radio Button belum dipilih");
        }
    }//GEN-LAST:event_hitungActionPerformed

    private void cobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobaActionPerformed
        // TODO add your handling code here:
        nama.setText("");
        tinggi.setText("");
        bb.setText("");
        ideal.setText("");
        hasil.setText("");
        saran.setText("");
        buttonGroup1.clearSelection();
        
    }//GEN-LAST:event_cobaActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Framemodul7_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Framemodul7_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Framemodul7_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Framemodul7_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Framemodul7_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton coba;
    private javax.swing.JTextField hasil;
    private javax.swing.JButton hitung;
    private javax.swing.JTextField ideal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton keluar;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField saran;
    private javax.swing.JTextField tinggi;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        ti = Double.valueOf(tinggi.getText());
        bt = Double.valueOf(bb.getText());
        
        if (jRadioButton1.isSelected()) {
            hi = (ti - 100) * 1;
        }else if (jRadioButton2.isSelected()) {
            hi = (ti - 104) * 1;
        }
        temp = Double.toString(hi.intValue());
        
        if(hi < bt){
            ideal.setText(temp);
            hasil.setText("Maaf "+nama.getText()+" , sepertinya anda Overweight");
            saran.setText("Banyaklah berolahraga dan hindari makanan berkolesterol");
        }else if(hi > bt){
            ideal.setText(temp);
            hasil.setText("Maaf "+nama.getText()+" , sepertinya anda Underweight");
            saran.setText("Banyaklah mengkonsumsi makanan yang berkarbohidrat");
        }else{
            ideal.setText(temp);
            hasil.setText("Halo "+nama.getText()+" , berat badan anda sudah ideal");
            saran.setText("Lanjutkan polam akan teratur dan gaya hidup sehat");
        }
    }
}
